spring:
  datasource:
    url: jdbc:h2:./db/test-springmvc
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    com.hellozjf.test.testspringmvc: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
custom:
  # ×î´ó¸½¼þ1M
  max-part-size: 1